services:
  frontend:
    build: ./progym-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./progym-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - progym-network
    stdin_open: true
    tty: true

  backend:
    build: ./progym-backend
    ports:
      - "5000:5000"
    env_file:
      - ./progym-backend/.env
    volumes:
      - ./progym-backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - progym-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: shahed
      MYSQL_DATABASE: progymdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - progym-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pshahed"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:

networks:
  progym-network:
    driver: bridge
