version: '3.8'

services:
  frontend:
    build: ./progym-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy   # ✅ Wait for backend to be healthy
    restart: always
    networks:
      - progym-network

  backend:
    build: ./progym-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=shahed
      - DB_NAME=progymdb
      - JWT_SECRET=yourjwtsecret
    depends_on:
      db:
        condition: service_healthy    # ✅ Wait for database to be healthy
    restart: always
    networks:
      - progym-network
    healthcheck:                      # ✅ Backend also has a healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: shahed
    volumes:
      - mysql-data:/var/lib/mysql           # Persist MySQL data
      - ./progymdb.sql:/docker-entrypoint-initdb.d/progymdb.sql  # Initialize DB
    restart: always
    networks:
      - progym-network
    healthcheck:                            # ✅ Added healthcheck for MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:  # ✅ Persistent volume for DB

networks:
  progym-network:
    driver: bridge
