const styles = {
  page: {
    backgroundColor: "#FFF6E0",
    fontFamily: "'Inter', sans-serif",
    color: "#272829",
    position: "relative",
    height: "100vh",
    overflow: "hidden",
  },
  navbar: {
    position: "fixed",
    top: 0,
    width: "100%",
    backgroundColor: "#61677A",
    display: "flex",
    justifyContent: "center",
    gap: "2rem",
    padding: "1rem 0",
    zIndex: 1000,
    boxShadow: "0 2px 8px rgba(216,217,218,0.4)",
  },
  navLink: {
    color: "#FFF6E0",
    textDecoration: "none",
    fontWeight: "600",
    fontSize: "1rem",
    letterSpacing: "0.5px",
  },
  scrollContainer: {
    scrollSnapType: "y mandatory",
    overflowY: "scroll",
    height: "100vh",
    scrollBehavior: "smooth",
  },
  snapSection: {
    scrollSnapAlign: "start",
    height: "100vh",
    paddingTop: "5rem",
    paddingInline: "1.5rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "1.5rem",
  },
  categoryTitle: {
    fontSize: "2rem",
    fontWeight: "700",
    marginBottom: "1rem",
    color: "#272829",
  },
  exerciseList: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: "1rem",
    width: "100%",
    maxWidth: "1000px",
  },
  card: {
    backgroundColor: "#FFF6E0",
    border: "1px solid #D8D9DA",
    borderRadius: "10px",
    padding: "1rem",
    boxShadow: "0 4px 10px rgba(216,217,218,0.3)",
    transition: "transform 0.25s ease",
  },
  cardTitle: {
    fontSize: "1.25rem",
    fontWeight: "600",
    marginBottom: "0.5rem",
  },
  cardSubtitle: {
    fontSize: "0.95rem",
    color: "#61677A",
  },
};

export default styles;
