// src/styles/GymBotStyle.js

const styles = {
  chatLayout: {
    display: 'flex',
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    backgroundColor: '#202123',
    color: '#fff',
    fontFamily: 'Arial, sans-serif',
    position: 'relative',
  },
  sidebar: {
    width: '260px',
    backgroundColor: '#000000',
    padding: '20px 16px',
    borderRight: '1px solid #343541',
    display: 'flex',
    flexDirection: 'column',
    transition: 'transform 0.3s ease-in-out',
    zIndex: 10,
  },
  sidebarHidden: {
    transform: 'translateX(-100%)',
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
  },
  toggleSidebarButton: {
    position: 'absolute',
    top: '20px',
    left: '20px',
    backgroundColor: '#343541',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    padding: '8px 10px',
    cursor: 'pointer',
    zIndex: 20,
  },
  sidebarTop: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  newChatButton: {
    padding: '10px 12px',
    backgroundColor: '#343541',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    cursor: 'pointer',
    textAlign: 'left',
  },
  sidebarTitle: {
    fontSize: '18px',
    marginBottom: '10px',
    color: '#D6BD98',
  },
  sidebarList: {
    listStyle: 'none',
    padding: 0,
    overflowY: 'auto',
    flex: 1,
  },
  sessionItem: {
    backgroundColor: '#343541',
    borderRadius: '6px',
    padding: '10px',
    color: '#fff',
    marginTop: '8px',
    fontSize: '13px',
    cursor: 'pointer',
  },
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#202123',
    padding: '20px 40px',
    overflow: 'hidden',
  },
  title: {
    fontSize: '22px',
    color: '#fff',
    textAlign: 'center',
    marginBottom: '16px',
  },
  chatBox: {
    flex: 1,
    backgroundColor: '#343541',
    borderRadius: '10px',
    padding: '20px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    marginBottom: '16px',
    border: '1px solid #2c2c2e',
  },
  message: {
    padding: '12px 16px',
    margin: '8px 0',
    borderRadius: '12px',
    maxWidth: '75%',
    lineHeight: '1.5',
    fontSize: '15px',
  },
  userMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#10a37f',
    color: '#fff',
  },
  botMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#444654',
    color: '#fff',
  },
  form: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    padding: '14px',
    borderRadius: '10px',
    border: '1px solid #555',
    fontSize: '15px',
    backgroundColor: '#343541',
    color: '#fff',
  },
  imageButton: {
    height: '42px',
    width: '42px',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
  },
};

export default styles;